server.port=8081
spring.application.name=core-service

# gRPC ??????: ????? Reference Service
grpc.client.reference-service.address=static://localhost:9090
grpc.client.reference-service.negotiation-type=plaintext

# ??????????? ? Trace ID
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] [%X{traceId:-N/A}] %-5level %logger{36} - %msg%n
logging.level.ru.iu3.lab4=DEBUG

spring.mvc.charset=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true