server.port=8080
grpc.client.reference-service.address=static://127.0.0.1:9091
grpc.client.reference-service.negotiation-type=plaintext
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId:-local}] %msg%n