server.port=8082
grpc.server.port=9090
spring.application.name=reference-service

# ??????????? ? Trace ID
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] [%X{traceId:-N/A}] %-5level %logger{36} - %msg%n
logging.level.ru.iu3.lab4=DEBUG

spring.mvc.charset=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true